### PR TITLE
Add blog post announcing v2022 Array API Standard release

### PR DESCRIPTION
**Pull request by kgryte**
This PR

- adds a blog post announcing the 2022 revision of the Array API standard.
- spends some time to covering what has transpired since the initial draft release in Nov 20, as no blog post was published after the final v2021 release.
- states that the focus for 2023 will be driving adoption among downstream array API consumers.

### CODE REVIEW

**Comment by kgryte** [comment]
As discussed in the 12 January 2022 consortium meeting, I've updated the blog post to announce the release of the test suite and array compatibility layer. I also fixed a few typos and grammatical errors.

This post should be ready for review.

**Comment by kgryte** [comment]
I've updated this post to note that the array API compat layer now support PyTorch.

**Comment by kgryte** [comment]
@rgommers Would you mind reviewing?

**Review by rgommers — APPROVED** [review]
This read really well. Thanks @kgryte. And apologies for the delay!

**Comment by rgommers** [comment]
Live now at https://data-apis.org/blog/array_api_v2022_release/

**Pull request merged**
